"""
Integration Tests — Extractor Agent → Database → Evaluator Agent
=================================================================
Scope  : User creation, SME profile upsert (with extracted JSON from a simulated
         LLM), document persistence, grant requirement injection, and readiness
         evaluation — all using an in-memory SQLite database.
         No real LLM calls are made; extracted data is hardcoded mock objects.
Execution: Runs locally via `python -m pytest` and in GitHub Actions CI.
Pass Condition: Parsed JSON from LLM saves into the DB without schema mismatch.
"""

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from backend.src.core.dag_router import (
    READINESS_THRESHOLD_PERCENT,
    build_application_checklist,
    build_application_summary,
    evaluate_grant_match,
)
from backend.src.database.db import (
    build_grant_application_snapshot,
    create_grant,
    create_user,
    get_company_documents,
    get_company_profile,
    rank_grants_for_user,
    upsert_company_document,
    upsert_company_profile,
    update_system_state,
)
from backend.src.database.models import (
    Base,
    CompanyDocument,
    Grant,
    GrantRequirement,
    RequirementSource,
    SMEProfile,
    SystemState,
    User,
)


# ──────────────────────────────────────────────────────────────────────────────
# FIXTURES — in-memory SQLite (isolated per test)
# ──────────────────────────────────────────────────────────────────────────────

@pytest.fixture()
def db():
    """Provide a fresh in-memory SQLite session for each test."""
    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
    )
    Base.metadata.create_all(bind=engine)
    Session = sessionmaker(bind=engine, autoflush=False, autocommit=False)
    session = Session()
    try:
        yield session
    finally:
        session.close()
        Base.metadata.drop_all(bind=engine)


@pytest.fixture()
def user(db):
    """Create and return a standard test user."""
    return create_user(db, username="techbina_user", email="test@techbina.com")


@pytest.fixture()
def tech_grant(db):
    """Hardcoded GrantRequirements mock object — MDEC Digital Grant."""
    return create_grant(db, {
        "title": "MDEC Digital Grant",
        "provider_name": "MDEC",
        "source_url": "https://mdec.my/grants/digital",
        "description": "Supports SMEs adopting digital tools.",
        "amount_min": 5_000,
        "amount_max": 50_000,
        "nationality": "Malaysia",
        "industry": "Technology",
        "eligibility_notes": "Open to Malaysian tech SMEs.",
        "application_deadline": "2026-12-31",
        "status": "open",
        "metadata_json": {"source": "test"},
        "requirements": [
            {
                "name": "SSM Certificate",
                "description": "Business registration certificate.",
                "source_type": "attached",
                "document_type": "ssm",
                "is_required": True,
            },
            {
                "name": "Latest Financial Statement",
                "description": "Audited or management accounts.",
                "source_type": "attached",
                "document_type": "financial_statement",
                "is_required": True,
            },
            {
                "name": "Pitch Deck",
                "description": "Auto-generated by Drafter Agent.",
                "source_type": "generated",
                "document_type": "pitch_deck",
                "is_required": True,
            },
        ],
    })


@pytest.fixture()
def general_grant(db):
    """Hardcoded GrantRequirements mock object — SME Corp Market Expansion Fund."""
    return create_grant(db, {
        "title": "Market Expansion Support Fund",
        "provider_name": "SME Corp",
        "nationality": "Malaysia",
        "industry": "General",
        "amount_max": 80_000,
        "status": "open",
        "metadata_json": {},
        "requirements": [
            {
                "name": "Company Profile",
                "source_type": "generated",
                "document_type": "company_profile",
                "is_required": True,
            },
            {
                "name": "Financial Statement",
                "source_type": "attached",
                "document_type": "financial_statement",
                "is_required": True,
            },
        ],
    })


# Simulated LLM extractor output — hardcoded, no token cost
LLM_EXTRACTED_TECHBINA = {
    "company_name": "TechBina Sdn Bhd",
    "industry": "Technology",
    "nationality": "Malaysia",
    "employee_count": 50,
    "target_grant_amount": 50_000,
    "summary": "AI-powered grant matching platform for Malaysian SMEs.",
    "annual_revenue": 600_000,
    "questionnaire_answers": {"q1": "yes", "q2": "growth"},
    "extracted_data": {
        "ssm_number": "1234567-A",
        "total_project_cost_rm": 120_000,
        "requested_funding_rm": 50_000,
        "ownership_majority": "Malaysian",
    },
}

LLM_DOCS_TECHBINA = [
    {"document_type": "ssm", "file_name": "ssm_cert.pdf", "status": "uploaded"},
    {"document_type": "financial_statement", "file_name": "financials_2024.pdf", "status": "uploaded"},
]


# ──────────────────────────────────────────────────────────────────────────────
# 1. USER CREATION (DB Write)
# ──────────────────────────────────────────────────────────────────────────────

def test_user_created_and_persisted(db):
    """Extractor step: user record must persist in DB with correct fields."""
    u = create_user(db, username="integ_user", email="integ@test.com", external_auth_id="uid_xyz")
    fetched = db.query(User).filter(User.id == u.id).first()
    assert fetched is not None
    assert fetched.username == "integ_user"
    assert fetched.email == "integ@test.com"
    assert fetched.external_auth_id == "uid_xyz"


def test_user_external_auth_id_is_unique(db):
    """Two users cannot share the same Firebase UID."""
    from sqlalchemy.exc import IntegrityError
    create_user(db, username="user_a", email="a@test.com", external_auth_id="same_uid")
    db.rollback() if False else None
    with pytest.raises(IntegrityError):
        create_user(db, username="user_b", email="b@test.com", external_auth_id="same_uid")


# ──────────────────────────────────────────────────────────────────────────────
# 2. SME PROFILE UPSERT (Extractor → DB — core integration path)
# ──────────────────────────────────────────────────────────────────────────────

def test_llm_extracted_profile_saves_without_schema_mismatch(db, user):
    """
    Pass Condition: Parsed JSON from the LLM correctly saves into the
    Relational Database without schema mismatch errors.
    """
    profile = upsert_company_profile(
        db=db,
        user_id=user.id,
        profile_data=LLM_EXTRACTED_TECHBINA,
        documents=LLM_DOCS_TECHBINA,
    )
    assert profile is not None
    assert profile.company_name == "TechBina Sdn Bhd"
    assert profile.industry == "Technology"
    assert profile.nationality == "Malaysia"
    assert profile.employee_count == 50
    assert profile.target_grant_amount == 50_000
    assert profile.annual_revenue == 600_000


def test_readiness_score_computed_and_stored_after_upsert(db, user):
    """After profile upsert with core docs, readiness_score must be persisted in DB."""
    profile = upsert_company_profile(
        db=db, user_id=user.id,
        profile_data=LLM_EXTRACTED_TECHBINA,
        documents=LLM_DOCS_TECHBINA,
    )
    db_profile = db.query(SMEProfile).filter(SMEProfile.user_id == user.id).first()
    assert db_profile.readiness_score == profile.readiness_score
    assert db_profile.readiness_score > 0


def test_profile_upsert_is_idempotent(db, user):
    """Calling upsert twice should update the row, not create a duplicate."""
    upsert_company_profile(db=db, user_id=user.id, profile_data=LLM_EXTRACTED_TECHBINA, documents=[])
    upsert_company_profile(db=db, user_id=user.id, profile_data={"company_name": "TechBina Sdn Bhd", "annual_revenue": 999_000}, documents=[])
    count = db.query(SMEProfile).filter(SMEProfile.user_id == user.id).count()
    assert count == 1
    updated = db.query(SMEProfile).filter(SMEProfile.user_id == user.id).first()
    assert updated.annual_revenue == 999_000


def test_extracted_data_json_merges_correctly(db, user):
    """Successive LLM extractions must merge into the JSON blob, not replace it."""
    upsert_company_profile(db=db, user_id=user.id, profile_data={"company_name": "TechBina", "extracted_data": {"ssm_number": "A123"}}, documents=[])
    upsert_company_profile(db=db, user_id=user.id, profile_data={"company_name": "TechBina", "extracted_data": {"total_project_cost_rm": 200_000}}, documents=[])
    profile = db.query(SMEProfile).filter(SMEProfile.user_id == user.id).first()
    assert profile.extracted_data.get("ssm_number") == "A123"
    assert profile.extracted_data.get("total_project_cost_rm") == 200_000


# ──────────────────────────────────────────────────────────────────────────────
# 3. DOCUMENT PERSISTENCE (Extractor → DB)
# ──────────────────────────────────────────────────────────────────────────────

def test_documents_saved_to_db_after_upsert(db, user):
    """Documents attached during profile upsert must be persisted with correct types."""
    upsert_company_profile(db=db, user_id=user.id, profile_data=LLM_EXTRACTED_TECHBINA, documents=LLM_DOCS_TECHBINA)
    docs = db.query(CompanyDocument).filter(CompanyDocument.user_id == user.id).all()
    doc_types = {d.document_type for d in docs}
    assert "ssm" in doc_types
    assert "financial_statement" in doc_types


def test_document_upsert_does_not_duplicate(db, user):
    """Uploading the same document twice must not create duplicate rows."""
    upsert_company_profile(db=db, user_id=user.id, profile_data=LLM_EXTRACTED_TECHBINA, documents=LLM_DOCS_TECHBINA)
    upsert_company_profile(db=db, user_id=user.id, profile_data=LLM_EXTRACTED_TECHBINA, documents=LLM_DOCS_TECHBINA)
    docs = db.query(CompanyDocument).filter(CompanyDocument.user_id == user.id).all()
    ssm_docs = [d for d in docs if d.document_type == "ssm"]
    assert len(ssm_docs) == 1


def test_document_standalone_upsert(db, user):
    """upsert_company_document should create a document row with correct metadata."""
    doc = upsert_company_document(db, user.id, {
        "document_type": "business_plan",
        "file_name": "plan.pdf",
        "file_url": "https://storage.example.com/plan.pdf",
        "status": "uploaded",
        "metadata": {"pages": 12},
    })
    assert doc.id is not None
    assert doc.document_type == "business_plan"
    assert doc.metadata_json == {"pages": 12}


# ──────────────────────────────────────────────────────────────────────────────
# 4. GRANT REQUIREMENT INJECTION (Hardcoded Mock Objects)
# ──────────────────────────────────────────────────────────────────────────────

def test_grant_requirements_saved_correctly(db, tech_grant):
    """Hardcoded GrantRequirements mock objects must persist with correct schema."""
    g = db.query(Grant).filter(Grant.id == tech_grant.id).first()
    assert g is not None
    assert len(g.requirements) == 3
    req_names = {r.name for r in g.requirements}
    assert "SSM Certificate" in req_names
    assert "Latest Financial Statement" in req_names
    assert "Pitch Deck" in req_names


def test_grant_requirement_source_types_persist(db, tech_grant):
    """Requirement source_type enum must persist correctly (attached vs generated)."""
    reqs = {r.name: r for r in tech_grant.requirements}
    assert reqs["SSM Certificate"].source_type == RequirementSource.ATTACHED
    assert reqs["Pitch Deck"].source_type == RequirementSource.GENERATED


def test_grant_is_required_flag_persists(db, tech_grant):
    """is_required flag must default to True for all injected requirements."""
    for req in tech_grant.requirements:
        assert req.is_required is True


# ──────────────────────────────────────────────────────────────────────────────
# 5. EVALUATOR AGENT — Grant Matching (DB → Evaluator)
# ──────────────────────────────────────────────────────────────────────────────

def test_evaluator_returns_drafter_track_for_ready_profile(db, user, tech_grant):
    """
    Evaluator Agent: full profile with SSM + financials matching a tech grant
    must produce readiness_score >= 80 and route to 'drafter'.
    """
    upsert_company_profile(db=db, user_id=user.id, profile_data=LLM_EXTRACTED_TECHBINA, documents=LLM_DOCS_TECHBINA)
    profile = get_company_profile(db, user.id)
    documents = get_company_documents(db, user.id)
    result = evaluate_grant_match(profile=profile, grant=tech_grant, documents=documents)
    assert result["readiness_score"] >= READINESS_THRESHOLD_PERCENT
    assert result["track"] == "drafter"


def test_evaluator_returns_coach_track_for_incomplete_profile(db, user, tech_grant):
    """Evaluator Agent: incomplete profile without core docs must route to 'coach'."""
    upsert_company_profile(db=db, user_id=user.id, profile_data={"company_name": "StartupX"}, documents=[])
    profile = get_company_profile(db, user.id)
    documents = get_company_documents(db, user.id)
    result = evaluate_grant_match(profile=profile, grant=tech_grant, documents=documents)
    assert result["track"] == "coach"


def test_evaluator_returns_profile_required_when_no_profile(db, tech_grant):
    """Evaluator Agent: no profile at all must return status='profile_required'."""
    result = evaluate_grant_match(profile=None, grant=tech_grant, documents=[])
    assert result["status"] == "profile_required"
    assert result["track"] == "onboarding"


def test_rank_grants_sorts_by_suitability_score(db, user, tech_grant, general_grant):
    """rank_grants_for_user must return grants in descending suitability order."""
    upsert_company_profile(db=db, user_id=user.id, profile_data=LLM_EXTRACTED_TECHBINA, documents=LLM_DOCS_TECHBINA)
    ranked = rank_grants_for_user(db, user.id)
    assert len(ranked) >= 2
    scores = [item["suitability_score"] for item in ranked]
    assert scores == sorted(scores, reverse=True)


def test_evidence_traces_are_populated(db, user, tech_grant):
    """Evaluator must produce evidence_traces with status MET/UNMET/UNKNOWN."""
    upsert_company_profile(db=db, user_id=user.id, profile_data=LLM_EXTRACTED_TECHBINA, documents=LLM_DOCS_TECHBINA)
    profile = get_company_profile(db, user.id)
    documents = get_company_documents(db, user.id)
    result = evaluate_grant_match(profile=profile, grant=tech_grant, documents=documents)
    assert len(result["evidence_traces"]) > 0
    for trace in result["evidence_traces"]:
        assert trace["status"] in {"MET", "UNMET", "UNKNOWN"}
        assert "requirement" in trace
        assert "reasoning" in trace


# ──────────────────────────────────────────────────────────────────────────────
# 6. APPLICATION SNAPSHOT (Full Pipeline: DB → Checklist → Summary)
# ──────────────────────────────────────────────────────────────────────────────

def test_application_snapshot_returns_correct_structure(db, user, tech_grant):
    """Full pipeline snapshot must return grant, checklist, readiness_score, track."""
    upsert_company_profile(db=db, user_id=user.id, profile_data=LLM_EXTRACTED_TECHBINA, documents=LLM_DOCS_TECHBINA)
    snapshot = build_grant_application_snapshot(db, user.id, tech_grant.id)
    assert snapshot is not None
    assert "grant" in snapshot
    assert "checklist" in snapshot
    assert "readiness_score" in snapshot
    assert "track" in snapshot


def test_application_snapshot_checklist_has_correct_items(db, user, tech_grant):
    """Checklist in snapshot must have one item per grant requirement."""
    upsert_company_profile(db=db, user_id=user.id, profile_data=LLM_EXTRACTED_TECHBINA, documents=LLM_DOCS_TECHBINA)
    snapshot = build_grant_application_snapshot(db, user.id, tech_grant.id)
    assert len(snapshot["checklist"]) == len(tech_grant.requirements)


def test_application_snapshot_none_for_unknown_grant(db, user):
    """Snapshot for a non-existent grant_id must return None gracefully."""
    result = build_grant_application_snapshot(db, user.id, grant_id=99999)
    assert result is None


def test_missing_documents_listed_in_coach_output(db, user, tech_grant):
    """When in coach track, missing_required_documents list must be non-empty."""
    upsert_company_profile(db=db, user_id=user.id, profile_data={"company_name": "StartupX"}, documents=[])
    snapshot = build_grant_application_snapshot(db, user.id, tech_grant.id)
    assert snapshot["track"] == "coach"
    assert len(snapshot["missing_required_documents"]) > 0
    assert snapshot["coach"] is not None


# ──────────────────────────────────────────────────────────────────────────────
# 7. SYSTEM STATE (DB Write — Evaluator Output → SystemState table)
# ──────────────────────────────────────────────────────────────────────────────

def test_system_state_written_after_profile_upsert(db, user):
    """SystemState row must be created automatically when a profile is upserted."""
    upsert_company_profile(db=db, user_id=user.id, profile_data=LLM_EXTRACTED_TECHBINA, documents=LLM_DOCS_TECHBINA)
    state = db.query(SystemState).filter(SystemState.user_id == user.id).first()
    assert state is not None
    assert state.readiness_score > 0


def test_system_state_track_reflects_readiness(db, user):
    """SystemState.current_track must be 'grant_matching' for score >= 60."""
    upsert_company_profile(db=db, user_id=user.id, profile_data=LLM_EXTRACTED_TECHBINA, documents=LLM_DOCS_TECHBINA)
    state = db.query(SystemState).filter(SystemState.user_id == user.id).first()
    assert state.current_track == "grant_matching"


def test_system_state_upsert_idempotent(db, user):
    """Calling update_system_state twice must update the row, not create a duplicate."""
    update_system_state(db, user.id, score=50.0, track="onboarding", trace={}, last_step="step_1")
    update_system_state(db, user.id, score=85.0, track="grant_matching", trace={}, last_step="step_2")
    count = db.query(SystemState).filter(SystemState.user_id == user.id).count()
    assert count == 1
    state = db.query(SystemState).filter(SystemState.user_id == user.id).first()
    assert state.readiness_score == 85.0
    assert state.current_track == "grant_matching"


# ──────────────────────────────────────────────────────────────────────────────
# 8. TIMEOUT HANDLING — P1 Critical
#    (Validates the system's behaviour under simulated timeout conditions
#     by checking that the route logic is resilient to missing/null data.)
# ──────────────────────────────────────────────────────────────────────────────

def test_evaluator_handles_none_profile_gracefully(db, tech_grant):
    """P1 Critical: None profile (e.g. timeout during onboarding) must not crash."""
    result = evaluate_grant_match(profile=None, grant=tech_grant, documents=[])
    assert isinstance(result, dict)
    assert result["track"] == "onboarding"


def test_evaluator_handles_empty_documents_gracefully(db, user, tech_grant):
    """P1 Critical: Empty documents list (e.g. upload timeout) must not crash."""
    upsert_company_profile(db=db, user_id=user.id, profile_data=LLM_EXTRACTED_TECHBINA, documents=[])
    profile = get_company_profile(db, user.id)
    result = evaluate_grant_match(profile=profile, grant=tech_grant, documents=[])
    assert isinstance(result, dict)
    assert "track" in result


def test_profile_upsert_with_empty_payload_does_not_crash(db, user):
    """P1 Critical: Empty extracted payload (LLM timeout stub) must not raise."""
    profile = upsert_company_profile(db=db, user_id=user.id, profile_data={"company_name": "Unknown Company"}, documents=[])
    assert profile is not None


def test_rank_grants_with_no_profile_does_not_crash(db, user, tech_grant):
    """P1 Critical: rank_grants_for_user with no profile must return valid list."""
    ranked = rank_grants_for_user(db, user.id)
    assert isinstance(ranked, list)
    for item in ranked:
        assert item["track"] == "onboarding"


def test_snapshot_with_no_documents_does_not_crash(db, user, tech_grant):
    """P1 Critical: Application snapshot with no documents uploaded must not crash."""
    upsert_company_profile(db=db, user_id=user.id, profile_data={"company_name": "TechBina"}, documents=[])
    snapshot = build_grant_application_snapshot(db, user.id, tech_grant.id)
    assert snapshot is not None
    assert "checklist" in snapshot
